### ISSUE TITLE
[BUG] `convert-formula` calls ex with unknown argument

### ISSUE THREAD

**Issue by stooj** [saltstack-formulas/template-formula#192]
## Your setup

Host OS: Archlinux

### Formula commit hash / release tag
f48a7275644d2baef06adb0d8e74b3c19fd2d8a0

---

### Describe the bug
When running `bin/convert-formula.sh`, the following error occurs multiple times:

```
ex: illegal option -- u                                                                                              
Usage: ex [- | -s] [-l] [-L] [-R] [-r [file]] [-t tag]    
       [-v] [-V] [-w size] [+cmd | -c cmd] file...
```

The `-u` flag is not available in `ex` (or even `vi` as far as I can tell).

Debian-based systems tend to have `/usr/bin/ex` symlinked to `/usr/bin/vim.basic`, so the `-u` flag will work. But on my Arch box, `/usr/bin/ex` is the ex binary.

This error means that none of the search & replacements for `TEMPLATE` work.

### Steps to reproduce the bug

(On an Arch installation)
- Clone the formula repo locally
- cd into the formula directory
- Run `bin/convert-formula.sh example`

### Expected behaviour
`convert-formula.sh` should complete without errors and replace TEMPLATE strings correctly.

### Additional context

Maybe checking to see if `ex` is really vim in ex clothing, and then excluding the `-u` as required would fix it and not break any existing vim users.

**Comment by myii** [comment]
@stooj You're right, this needs to be fixed but it's not enough to drop the `-u`, since it was put in to avoid Vim-like behaviours where it is symlinked; that also causes the script to fail.  So one idea of what could be done is use something like:

```bash
EX_TGT=$(readlink -f $(which ex))
```

We can then set `EX` to be either `ex` or `ex -u NONE` depending on the value of `EX_TGT`.  What does that return for you, by the way?

CC: @dafyddj.

**Comment by myii** [comment]
OK, I've tested that across all of the unique platforms we handle:

* https://travis-ci.org/github/myii/template-formula/builds/670515543
  - Only Arch Linux fails!

Summary of results:

`EX_TGT` | Platforms
--- | ---
`/usr/bin/vim.tiny` | Debian, Ubuntu
`/usr/bin/vi` | CentOS (7 & 8), Fedora, Amazon Linux (2)
`/bin/vi` | CentOS (6), Amazon Linux (1)
`/usr/bin/vim-nox11` | OpenSUSE
`/usr/bin/ex` | Arch Linux

So where `EX_TGT` points directly to the `/usr/bin/ex` binary, we shouldn't use `-u NONE`.

---

Note: apparently it's better to use `type` rather than `which`, so that should be used instead:

* https://stackoverflow.com/questions/7522712/how-can-i-check-if-a-command-exists-in-a-shell-script

**Comment by myii** [comment]
I suppose another way is to simply test if `ex -u NONE` results in an error and then avoid using `-u NONE`.

**Comment by stooj** [comment]
Sorry I didn't catch this earlier.

Thanks so much for looking into this. I tried to patch this using a similar approach to your suggestion in https://github.com/saltstack-formulas/template-formula/issues/192#issuecomment-608373054, but vanilla ex chokes on the regular expressions:

```
$ DEBUG=true bin/convert-formula.sh example
++ grep vim
+++ command -v ex
++ readlink -f /usr/bin/ex
+ '[' ']'
+ EX=ex
+ args example
+ '[' 1 -ne 1 ']'
+ NEW_NAME=example
+ echo example
+ grep -E --quiet --invert-match '^[a-z0-9]+$'
+ echo bin docs test
+ grep --quiet --word-regexp example
+ convert_formula
++ echo 'feat: initial commit'
++ git commit-tree 'HEAD^{tree}'
+ git reset 0c46405c89bedd6fb56f7df9788ad90275e3a57a
+ git rm --quiet bin/convert-formula.sh AUTHORS.md CHANGELOG.md docs/_static/css/custom.css docs/AUTHORS.rst docs/CHANGELOG.rst docs/conf.py docs/CONTRIBUTING_DOCS.rst docs/index.rst
+ git mv TEMPLATE example
+ grep --recursive --files-with-matches --exclude-dir=.git TEMPLATE .
+ xargs -L 1 ex -sc '%s/TEMPLATE/example/g|x'
+ ex -sc '%s/^.. <REMOVEME\_.\{-}.. REMOVEME>/None/g|x' docs/README.rst
Bad number in regular expression

q
+ ex -sc '%s/^\s*# <REMOVEME\_.\{-}# REMOVEME>\n//g|x' .travis.yml
} expected after \

q
+ ex -sc '%s/^\s*# <REMOVEME\_.\{-}# REMOVEME>\n//g|x' .rubocop.yml
} expected after \

```

I will keep experimenting.

**Comment by dafyddj** [comment]
There's a couple of other options here. 
The  original reason for using `ex/vi` was to get around a minor incompatibility between GNU and BSD (Mac) `sed`.
There's a workaround for that incompatibility [here](https://stackoverflow.com/a/22084103) or we could force a Mac user (i.e. me) to install GNU `sed` using a package manager like homebrew before running the script.
