### ISSUE TITLE
[QUESTIONS] Best practice to include other formulas?

### ISSUE THREAD

**Issue by nikAizuddin** [saltstack-formulas/template-formula#202]
Hi, what is the best way to include other formulas in a formula.

For example, I want to create a `podman-formula` repository for Podman installation on Centos7, but requires [elrepo-formula](https://github.com/saltstack-formulas/elrepo-formula).

So, if I want to add [elrepo-formula](https://github.com/saltstack-formulas/elrepo-formula) as submodule, should I put `elrepo-formula` into `TEMPLATE/subcomponent/elrepo-formula`?

**Comment by myii** [comment]
@nikAizuddin When we're developing formulas within this org, we tend to avoid cross-formula (hard) dependencies, since that can lead to difficulties for end users.  However, if you are maintaining your own formulas, then you can achieve this by using `include` in your state files, such as [this example](https://github.com/saltstack-formulas/gitolite-formula/blob/080d4624a0c66783620ea6e9aab35a113a920564/gitolite/init.sls#L5-L7):

```sls
include:
  - git
  - perl
```

For a really detailed example, you can look at the [opensds-formula](https://github.com/saltstack-formulas/opensds-formula/search?q=include&unscoped_q=include).

**Comment by nikAizuddin** [comment]
@myii thanks, I'll take a look at the examples.
