### ISSUE TITLE
Formula based off template can't be moved from the root salt directory

### ISSUE THREAD

**Issue by redundancydisorder** [saltstack-formulas/template-formula#22]
The template assumes the formula will always live in salt://<formulaname> as noted here:

{% from "template/map.jinja" import template with context %}

It would be better to use: 

{% from tpldir ~ "/map.jinja" import template with context %}

**Comment by myii** [comment]
@redundancydisorder Welcome to GitHub!  And thanks for this request -- did we just communicate on Slack?

The idea is an excellent one.  However, there is a stumbling block that we're going to have to consider:

- [ ] Find a solution for `tpldir` not working in template files, see https://github.com/saltstack/salt/issues/41195.

There may be a solution soon:

- [ ] Evaluate if relative paths can be used, see https://github.com/saltstack/salt/pull/47490.

**Comment by redundancydisorder** [comment]
Yes I was on the salt slack. I have been testing internally modifying existing formulas (users, bind, dhcpd, apache) to function when not in the root salt directory. I was just hoping that addressing this in the template as well as changes to popular formulas would change the overall formula design to be more portable.

**Comment by myii** [comment]
@redundancydisorder Unfortunately, we can't apply the changes across formulas until we get a solution from upstream, as linked in my comment above.  Looking at the [commit](https://github.com/saltstack/salt/commit/160cdb20fda095c0e7f79a734873d6a4864ce8d0) tags:

* `develop (#47490) v2019.2.0rc2 v2019.2.0rc1 v2019.2 v2018.11`

Looks like we're a bit stuck, since our formulas have to work with Salt versions that are still [officially supported](https://github.com/saltstack-formulas/salt-formula/pull/398#issuecomment-459565043).  This is going to be a tough one.

**Comment by myii** [comment]
@redundancydisorder In terms of `tpldir` working in templates, there is the workaround of [sending it through as a context variable](https://github.com/saltstack-formulas/mysql-formula/pull/184#issuecomment-398193878).

**Comment by myii** [comment]
A probable solution introduced with 068a94d:
https://github.com/saltstack-formulas/template-formula/blob/068a94d3a242ec818640205626b011f8e53acf1a/template/macros.jinja#L46

**Comment by myii** [comment]
@redundancydisorder This should work for you now.
