### ISSUE TITLE
Should we restructure the init file?

### ISSUE THREAD

**Issue by gravyboat** [saltstack-formulas/template-formula#9]
This came up here: https://github.com/saltstack-formulas/haproxy-formula/pull/28 where the user wants to only include specific items. This seems redundant to me, and as pointed out by @puneetk it's the default used here: https://github.com/saltstack-formulas/template-formula/blob/master/template/init.sls 

I should note that I HATE this structure of including other states in the init, it just seems lazy to me, and confusing for new users who are not explicitly including states. @whiteinge What's your opinion of modifying the init to remove this sort of inclusion?

**Comment by whiteinge** [comment]
I'm not a fan of include-only sls files because:

1. They insinuate that a formula is a monolithic thing that can be run in whole.

  A formula should be a library -- a collection of mostly unrelated operations that all revolve around a single bit of tech.

  E.g., I don't care about `apache.mod_php` but I do care about `apache.mod_wsgi`. Both files are in the same formula because they both operation on Apache but I'm only likely to run one. I tend to think of formulas as "Here's a collection of things I can make Apache do." rather than a "Here's something I can run to fully set up all of Apache."

2. They're often opinionated.

  If the `init.sls` file includes both the server and the client and the config file and the third-party repo then the default behavior for that formula is making some specific choices for me the user. It's not a big deal because I can ignore it and just use the files I care about but I agree that is confusing for new users and misdirects how to think of formulas (point 1).

3. They're not required.

  A common misconception is that (like Python) every directory must have an `init.sls` file and so they're often included in formulas by default or habit. A layout like `myformula/{file1.sls,file2.sls}` with no `init.sls` works just fine, while reducing noise and repetition. I'm definitely guilty of including them out of habit but in recent years I often leave them out entirely.

4. They're easy to overuse and make non-flat structures.

  An `apache/config/init.sls` is a useful way to group non-sls files together like `apache/config/{readhat.conf,ubuntu.conf}` but still retain the nice `apache.config` path. But a deep path like `someformula/subdir/subsubdir/subsubsubdir` with `init.sls` files at each level that try to include and encapsulate all the functionality contained at each level is madness and bears all the same anti-patterns as deep OOP class hierarchies. Favor composition over inheritance. :-)

5. They can make ordering (really) hard.

  `include` declarations are useful for pulling in an external state `id` that you need in your own `requisite` or `requisite_in` declaration but they're just awful for ordering. Sure Salt processes the includes in source-order but if any of the states that were included use `order` or have inter-dependencies or requisites of their own then _all bets are off_. Include-only sls files add to the confusion. Salt states are declarative and relationships should be defined explicitly via requisites. Source-order execution is a nice shorthand but should not be relied on for large state trees. (Unless you very conciously take the Lyft no-requisites approach to ordering.)

6. They're broken (for certain uses).

  https://github.com/saltstack/salt/issues/10852 is a long-standing issue. I'm not aware that it's on anyone's immediate radar to fix.

All that said, I do understand why people use them and like them. They are sometimes quite useful. They're not going away and the above bug does need to be fixed. They should be a tool for advanced users, not a best practice, and not recommended in a template.

**Comment by iggy** [comment]
/me claps for @whiteinge 

Well said.

**Comment by gravyboat** [comment]
If people prefer to have a file that includes everything they should just make `all_the_things.sls`.

**Comment by puneetk** [comment]
> They insinuate that a formula is a monolithic thing that can be run in whole.
For me the top level init will do whats global, as in a default implementation. So in the case of your example it will setup apache, dirs and packages. If you want some parts of apache like wsgi or the like that would be handled by formula.apache.plugins and configured by a pillar. Then formula.apache.plugins is included in top level init file. Basically the formula module is configured by the pillars completely. 

> They're often opinionated.
Similar as above, the init file should include either, or both client/server based on the config from the pillar. So you can see what you are doing on the minion using a pillar.get <formulaname>

**Comment by whiteinge** [comment]
@puneetk I should stress more that neither approach is objectively wrong -- both have pros and cons. If you like the pattern and it works for you, keep using it! :+1: 

I don't recommend it in the Best Practices doc for the reasons I mentioned above and IMO the template formula should reflect the recommendations in that doc.

**Comment by whiteinge** [comment]
Also individual formulas should do what works best for them and that will often reflect the tastes of the author. That's a good thing! If it works then it works. If it doesn't work then users will file issues to complain. :stuck_out_tongue_winking_eye:

**Comment by puneetk** [comment]
True, we should spend the time to bring the template formula close to whats in the best practices doc and vice versa, I nominate @gravyboat since he started this thread :dash:

**Comment by tracphil** [comment]
I use both. I think the init.sls should stay the way it is in the template formula.

In this case, there isn't a client/server but the structure I like.:

https://github.com/amerinap/gdnsd-formula/blob/production/gdnsd/init.sls

It keeps things nice and tidy. I think this is especially helpful for people starting to use SaltStack.

Btw, I am just starting to rewrite formulas for git_fs and reclass as an ENC, so any tips would be appreciated.

I also have separate sls files especially for client/server applications, but those are usually more advanced configurations. There is a lot of flexibility in SaltStack and at the end of the day, it should be easy to understand and I think the example formula starts people off on the right foot.

**Comment by marco-m** [comment]
Hello, what the status?

**Comment by johnkeates** [comment]
I think the status is: we leave it as-is because there is no 'better way' unless you really want to break stuff with no profit in the end.

**Comment by marco-m** [comment]
Thanks for the quick answer :-) Then this issue could be closed as wont fix ? :-)
